openapi: 3.0.1
info:
  title: Authentication and Archival API
  description: API documentation for authentication and archival configuration
  version: 1.0.0
servers:
  - url: http://localhost:8084/api/v1

paths:
  /auth/signup:
    post:
      summary: User Signup
      description: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [ROLE_ADMIN, ROLE_NON_ADMIN]
      responses:
        "200":
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  userName:
                    type: string
                  role:
                    type: string

  /auth/signin:
    post:
      summary: User Signin
      description: Authenticates a user and returns a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  role:
                    type: string

  /archival/configuration:
    post:
      summary: Set Archival Configuration
      description: Configures the archival settings for a table
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tableName:
                  type: string
                archiveAfter:
                  type: integer
                archivalTimeUnit:
                  type: string
                  enum: [DAYS, WEEKS, MONTHS]
                deleteAfter:
                  type: integer
                deleteAfterTimeUnit:
                  type: string
                  enum: [DAYS, WEEKS, MONTHS]
      responses:
        "200":
          description: Configuration saved successfully

    get:
      summary: Get Archival Configuration
      description: Retrieves the current archival configuration
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  tableName:
                    type: string
                  archiveAfter:
                    type: integer
                  archivalTimeUnit:
                    type: string
                  deleteAfter:
                    type: integer
                  deleteAfterTimeUnit:
                    type: string
