-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users (
                                            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
                                            INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
),
    created_date_time timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role smallint NOT NULL,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT users_role_check CHECK (role >= 0 AND role <= 1)
    ) TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users OWNER to postgres;

-- Table: public.archival_criteria

-- DROP TABLE IF EXISTS public.archival_criteria;

CREATE TABLE IF NOT EXISTS public.archival_criteria (
                                                        id BIGINT GENERATED ALWAYS AS IDENTITY,
                                                        table_name CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    archive_after INTEGER NOT NULL,
    archival_time_unit CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    delete_after INTEGER NOT NULL,
    delete_after_time_unit CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    archival_column_name CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    created_date_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_modified_date_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT archival_criteria_pkey PRIMARY KEY (id)
    ) TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.archival_criteria OWNER TO postgres;


-- Table: public.user_table_assignments

-- DROP TABLE IF EXISTS public.user_table_assignments;

CREATE TABLE IF NOT EXISTS public.user_table_assignments (
                                                             id BIGINT GENERATED ALWAYS AS IDENTITY, -- Auto-incrementing ID
                                                             user_name CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    table_names CHARACTER VARYING(255) COLLATE pg_catalog."default" NOT NULL,
    created_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_table_assignments_pkey PRIMARY KEY (id)
    ) TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_table_assignments OWNER TO postgres;


-- Table: public.student

-- DROP TABLE IF EXISTS public.student;

CREATE TABLE IF NOT EXISTS public.student (
                                              id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
                                              INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1
),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT student_email_key UNIQUE (email)
    ) TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.student OWNER to postgres;

-------- Sample record -------------
INSERT INTO public.student (name, email, date_of_birth, created_at)
VALUES
    ('Alice Johnson', 'alice1@example.com', '1995-05-14', '2024-01-10 12:34:56'),
    ('Bob Smith', 'bob2@example.com', '1998-09-23', '2024-07-15 08:20:30'),
    ('Charlie Brown', 'charlie3@example.com', '2000-02-10', '2024-05-22 16:45:10'),
    ('David Lee', 'david4@example.com', '1997-11-11', '2024-03-14 10:10:10'),
    ('Emma Wilson', 'emma5@example.com', '1996-07-19', '2024-12-01 09:05:20'),
    ('Frank Miller', 'frank6@example.com', '1999-04-02', '2024-06-30 18:30:45'),
    ('Grace Hall', 'grace7@example.com', '2001-06-25', '2024-05-08 14:15:00'),
    ('Henry Adams', 'henry8@example.com', '1994-03-05', '2024-02-20 11:50:30'),
    ('Isla Martinez', 'isla9@example.com', '2002-10-12', '2024-04-17 21:10:05'),
    ('Jack Taylor', 'jack10@example.com', '1993-12-31', '2024-07-29 06:40:55');
-------------------------------------